// NOTE: Current behavior: navigation reads static Learn fixtures.
// TODO: Correct /learns links to /learn, show readable titles/descriptions and
// breadcrumbs, and handle published content plus empty states.
// See docs/developer-guide.md, Learn.

import { Card, CardTitle } from "@/components/ui/card";
import type { Metadata } from "next";
import Link from "next/link";
import { getTopics } from "@/lib/learn/queries";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Learn() {
  const topics = getTopics();

  return (
    <>
      {/* TODO: Show the page title and description from content data. */}
      <section>
        <h2>Learn</h2>
        <p></p>
      </section>

      {/* NOTE: Topic selection is the first step of the Learn hierarchy. */}
      <section>
        <h3>Topics</h3>
        <div className=" grid grid-cols-3 gap-4 mt-2">
          {topics.map((topic, index) => (
            <Link href={`/learns/${topic.id}`} key={index}>
              <Card>
                <CardTitle>{topic.title}</CardTitle>
              </Card>
            </Link>
          ))}
        </div>
      </section>
    </>
  );
}
