import { Card, CardTitle } from "@/components/ui/card";
import type { Metadata } from "next";
import Link from "next/link";
import { getTopics } from "@/lib/learn/queries";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Learn() {
  const topics = getTopics();

  return (
    <>
      {/* 
    NOTE: Title and a little word about this page.
    */}
      <section>
        <h2>Learn</h2>
        <p></p>
      </section>

      {/* 
      NOTE: Big topics are can chosen with a little bit word of explanation.
      */}
      <section>
        <h3>Topics</h3>
        <div className=" grid grid-cols-3 gap-4 mt-2">
          {topics.map((topic, index) => (
            <Link href={`/learns/${topic.id}`} key={index}>
              <Card>
                <CardTitle>{topic.title}</CardTitle>
              </Card>
            </Link>
          ))}
        </div>
      </section>
    </>
  );
}
