import HomeFooter from "@/components/layouts/home-footer";
import HomeHeader from "@/components/layouts/home-header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      <HomeHeader />
      <main className="container mx-auto px-4 my-4 flex flex-col gap-4">{children}</main>
      <HomeFooter />
    </>
  );
}
